[project]
name = "advion-io"
version = "0.1.0"
description = "Wrapper-free Python bindings for Advion mass spectrometers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
]
